app:
  ingress:
    internal:
      enabled: true

  #health: "/health"
  # health checks off
  readinessProbe: "null"
  livenessProbe: "null"

  port: 80 # this is the port for the pod

  extraEnv:
    BACKEND_HOST_NAME: # gets set by the gitlab pipeline as the name is created there
    BACKEND_PORT: "8080"

